/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedProjectIdRouteImport } from './routes/_authed/$projectId'
import { Route as AuthedNewRouteImport } from './routes/_authed/new'
import { Route as AuthedProjectIdIndexRouteImport } from './routes/_authed/$projectId/index'
import { Route as AuthedProjectIdSettingsRouteImport } from './routes/_authed/$projectId/settings'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectIdRoute = AuthedProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNewRoute = AuthedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectIdIndexRoute = AuthedProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedProjectIdRoute,
} as any)
const AuthedProjectIdSettingsRoute = AuthedProjectIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/$projectId': typeof AuthedProjectIdRouteWithChildren
  '/new': typeof AuthedNewRoute
  '/$projectId/settings': typeof AuthedProjectIdSettingsRoute
  '/$projectId/': typeof AuthedProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/new': typeof AuthedNewRoute
  '/': typeof AuthedIndexRoute
  '/$projectId/settings': typeof AuthedProjectIdSettingsRoute
  '/$projectId': typeof AuthedProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/$projectId': typeof AuthedProjectIdRouteWithChildren
  '/_authed/new': typeof AuthedNewRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/$projectId/settings': typeof AuthedProjectIdSettingsRoute
  '/_authed/$projectId/': typeof AuthedProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$projectId'
    | '/new'
    | '/$projectId/settings'
    | '/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/new' | '/' | '/$projectId/settings' | '/$projectId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/$projectId'
    | '/_authed/new'
    | '/_authed/'
    | '/_authed/$projectId/settings'
    | '/_authed/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$projectId': {
      id: '/_authed/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof AuthedProjectIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/new': {
      id: '/_authed/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthedNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$projectId/': {
      id: '/_authed/$projectId/'
      path: '/'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof AuthedProjectIdIndexRouteImport
      parentRoute: typeof AuthedProjectIdRoute
    }
    '/_authed/$projectId/settings': {
      id: '/_authed/$projectId/settings'
      path: '/settings'
      fullPath: '/$projectId/settings'
      preLoaderRoute: typeof AuthedProjectIdSettingsRouteImport
      parentRoute: typeof AuthedProjectIdRoute
    }
  }
}

interface AuthedProjectIdRouteChildren {
  AuthedProjectIdSettingsRoute: typeof AuthedProjectIdSettingsRoute
  AuthedProjectIdIndexRoute: typeof AuthedProjectIdIndexRoute
}

const AuthedProjectIdRouteChildren: AuthedProjectIdRouteChildren = {
  AuthedProjectIdSettingsRoute: AuthedProjectIdSettingsRoute,
  AuthedProjectIdIndexRoute: AuthedProjectIdIndexRoute,
}

const AuthedProjectIdRouteWithChildren = AuthedProjectIdRoute._addFileChildren(
  AuthedProjectIdRouteChildren,
)

interface AuthedRouteChildren {
  AuthedProjectIdRoute: typeof AuthedProjectIdRouteWithChildren
  AuthedNewRoute: typeof AuthedNewRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedProjectIdRoute: AuthedProjectIdRouteWithChildren,
  AuthedNewRoute: AuthedNewRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
